// Phase-1 & 2 Constants
export const ADMISSION_STATUS = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    UNDER_SCRUTINY: 'UNDER_SCRUTINY',
    SCRUTINY_APPROVED: 'SCRUTINY_APPROVED',
    SCRUTINY_REJECTED: 'SCRUTINY_REJECTED',
    INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
    INTERVIEW_PASSED: 'INTERVIEW_PASSED',
    INTERVIEW_FAILED: 'INTERVIEW_FAILED',
    DOCUMENTS_VERIFIED: 'DOCUMENTS_VERIFIED',
    DOCUMENTS_REJECTED: 'DOCUMENTS_REJECTED',
    FEE_PENDING: 'FEE_PENDING',
    FEE_PAID: 'FEE_PAID',
    FEE_VERIFICATION_PENDING: 'FEE_VERIFICATION_PENDING',
    FEE_VERIFIED: 'FEE_VERIFIED',
    FEE_REJECTED: 'FEE_REJECTED',
    GUIDE_ALLOCATED: 'GUIDE_ALLOCATED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    PET_EXEMPTION_REQUESTED: 'PET_EXEMPTION_REQUESTED',
    PET_EXEMPTION_APPROVED: 'PET_EXEMPTION_APPROVED',
    PET_EXEMPTION_REJECTED: 'PET_EXEMPTION_REJECTED',
    GUIDE_ACCEPTED_BY_STUDENT: 'GUIDE_ACCEPTED_BY_STUDENT',
    GUIDE_ACCEPTED_BY_APPLICANT: 'GUIDE_ACCEPTED_BY_APPLICANT',
    GUIDE_REJECTED: 'GUIDE_REJECTED',
    ADMISSION_CONFIRMED: 'ADMISSION_CONFIRMED',
    INTAKE_APPROVED: 'INTAKE_APPROVED',
    INTAKE_REJECTED: 'INTAKE_REJECTED',
} as const;

export const APPLICATION_TYPE = {
    PET: 'PET',
} as const;

export const CANDIDATE_TYPE = {
    INTERNAL: 'INTERNAL',
    EXTERNAL: 'EXTERNAL',
} as const;
